-- *************************************
-- DBS301 - Week 10, Lecture Demo
-- DML, DDL, CRUD
-- Nov 11, 2019
-- *************************************

-- Data, Structure, and OOPs!
-- DDL - Data Definition Language
-- - Structure
-- DML - Data Manipulation Language
        -- CRUD
        -- CREATE, READ, UPDATE, DELETE
        -- INSERT SELECT UPDATE DELETE
        
-- DDL
CREATE TABLE w10_LuRoles (
    roleID int PRIMARY KEY,
    roleName varchar(25) NOT NULL CHECK(length(roleName) >= 5)
    );
INSERT INTO w10_LuRoles VALUES (0, 'undetermined');
SELECT * FROM w10_LuRoles;

CREATE TABLE w10_Movies (
    movieID int   GENERATED BY DEFAULT ON NULL AS IDENTITY    PRIMARY KEY,
    movieName varchar(50) NOT NULL,
    lengthMin int CHECK(lengthMin >=60 OR lengthMin IS NULL)
    );
    
CREATE TABLE w10_People (
    peopleID int GENERATED BY DEFAULT ON NULL AS IDENTITY  PRIMARY KEY,
    pLastName varchar(30) NOT NULL,
    pFirstName varchar(30) NOT NULL,
    DOB date,
    DOD date);
    
CREATE TABLE w10_Roles (
    rID int GENERATED BY DEFAULT ON NULL AS IDENTITY  PRIMARY KEY,
    peopleID int,
    movieID int,
    roleID int,
    dateEffective date DEFAULT sysdate,
    CONSTRAINT roles_movie_fk FOREIGN KEY (movieID) REFERENCES w10_movies(movieID)
    );
    
ALTER TABLE w10_Roles 
    ADD CONSTRAINT roles_fk FOREIGN KEY (roleID) REFERENCES w10_LuRoles(roleID);
    
ALTER TABLE w10_Roles
    ADD CONSTRAINT people_roles_fk FOREIGN KEY (peopleID) REFERENCES w10_People(peopleID);
    
-- DML
SELECT * FROM w10_LuRoles;
INSERT INTO w10_LuRoles (roleID, roleName) VALUES (1, 'Actor');
INSERT INTO w10_LuRoles VALUES (2, 'Actress');
INSERT ALL
    INTO w10_LuRoles VALUES (3, 'Director')
    INTO w10_LuRoles VALUES (4, 'Producer')
    INTO w10_LuRoles VALUES (5, 'Executive Producer')
    SELECT 1 FROM dual;
COMMIT;


SELECT * FROM w10_people;
INSERT INTO w10_People (pLastName, pFirstName)
    VALUES ('MacDonald', 'Robert');
INSERT INTO w10_People (peopleID, pLastName, pFirstName)
    VALUES (4, 'MacKenzie', 'Bob');
INSERT INTO w10_People (peopleID, pLastName, pFirstName)
    VALUES (7, 'MacKenzie', 'Doug');
INSERT INTO w10_People (pLastName, pFirstName)
    VALUES ('MacDonald', 'Clint');
    
UPDATE w10_people SET pFirstName = 'Dave' WHERE peopleID = 8;
-- NOTE PRIMARY KEY WAS USED


CREATE TABLE w10_TempTable AS
    SELECT pFirstName AS FN, pLastName AS LN, DOB
        FROM w10_people
        WHERE pFirstName IS NOT NULL;
        
CREATE TABLE w10_TempTable2 AS 
    SELECT * FROM w10_People;